apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-sendgrid-exporter.fullname" . }}
  labels:
    {{- include "prometheus-sendgrid-exporter.labels" . | nindent 4 }}
data:
  SENDGRID_API_KEY: {{ .Values.exporter.sendgrid.apikey | quote }}
  METRICS_ENDPOINT: {{ .Values.exporter.endpoint | quote }}
  LISTEN_ADDR: "0.0.0.0:{{ .Values.service.port }}"
