apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-sendgrid-exporter.fullname" . }}
  labels:
    {{- include "prometheus-sendgrid-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-sendgrid-exporter.labels" . | nindent 6 }}
  endpoints:
  - port: http
